// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdobDXy07Lz-FgR-OCfJ3sQZY1hA6R9X8',
    appId: '1:270857418441:web:d1ef39fa19f50222563f18',
    messagingSenderId: '270857418441',
    projectId: 'mini-whatsapp-d5250',
    authDomain: 'mini-whatsapp-d5250.firebaseapp.com',
    storageBucket: 'mini-whatsapp-d5250.appspot.com',
    measurementId: 'G-FMVD9F8V4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1KliLRoA6t_Q-RfJ1_TM3XGVTXgUCnO0',
    appId: '1:270857418441:android:f21b366192153496563f18',
    messagingSenderId: '270857418441',
    projectId: 'mini-whatsapp-d5250',
    storageBucket: 'mini-whatsapp-d5250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkfo-zJDWPegpaIpgly6Befu7zcSt-AH8',
    appId: '1:270857418441:ios:c947e5e8c85c529d563f18',
    messagingSenderId: '270857418441',
    projectId: 'mini-whatsapp-d5250',
    storageBucket: 'mini-whatsapp-d5250.appspot.com',
    iosBundleId: 'com.example.miniWhatsapp',
  );
}
